package org.omg.PortableInterceptor;


/**
* org/omg/PortableInterceptor/INACTIVE.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/java_re/workspace/8-2-build-macosx-x86_64/jdk8u92/6642/corba/src/share/classes/org/omg/PortableInterceptor/Interceptors.idl
* Thursday, March 31, 2016 9:24:50 PM PDT
*/

public interface INACTIVE
{

  /** Object adapter state that causes all requests to be discarded.
     * This state indicates that the adapter is shutting down.
     */
  public static final short value = (short)(3);
}
